Modified

diff --git a/.github/workflows/visto-bueno.yml b/.github/workflows/visto-bueno.yml
--- a/.github/workflows/visto-bueno.yml
+++ b/.github/workflows/visto-bueno.yml
@@ -6,6 +6,7 @@ on:
       branch:
         description: "Branch to scan"
         required: true
+
       repo:
         description: "Repositorio"  
         required: true
@@ -13,8 +14,6 @@ on:
 jobs:
   scan-html:
     runs-on: ubuntu-latest
-    outputs:
-     status: ${{ steps.html_check.outputs.status }}
     steps:
     - name: Checkout code
       uses: actions/checkout@v3
@@ -27,7 +26,6 @@ jobs:
           ls -la target_repo
 
     - name: Run HTML Quality Check
-      id: html_check
       run: |
           echo "Running HTML quality check..."
 
@@ -42,36 +40,29 @@ jobs:
             # Search for comments in HTML files
             MATCHES=$(grep -r -iE "$PATTERN" "$REPO_DIR"/*.html || true)
 
-            # Write result to file
-            echo "Repository: ${{ github.event.inputs.repo }}" > result.txt
-            echo "Branch: ${{ github.event.inputs.branch }}" >> result.txt
-            echo "Component: HTML Quality Check" >> result.txt
-            echo "" >> result.txt
-
             if [ -n "$MATCHES" ]; then
-              echo "Comentarios encontrados en los archivos HTML:" >> result.txt
-              echo "$MATCHES" >> result.txt
-              echo "" >> result.txt
-              echo "El VB ha sido rechazado." >> result.txt
-              echo "-------------------------------------" >> result.txt
-              echo "status=fail" >> $GITHUB_ENV
+              echo "-------------------------------------"
+              echo "Comentarios encontrados en los archivos HTML:"
+              echo "$MATCHES"
+              echo "-------------------------------------"
+              exit 1  # Fail the job if comments are found
             else
-              echo "No se encontraron comentarios en los archivos HTML." >> result.txt
-              echo "El VB ha sido aprobado." >> result.txt
-              echo "-------------------------------------" >> result.txt
-              echo "status=pass" >> $GITHUB_ENV
+              echo "-------------------------------------"
+              echo "No se encontraron comentarios en los archivos HTML."
+              echo "-------------------------------------"
+              # Exit with code 0 to indicate success
             fi
+            
           else
             echo "Error: Directory $REPO_DIR does not exist."
             exit 1
           fi
-
-  upload-result:
+  approval-status:
     runs-on: ubuntu-latest
     needs: scan-html
     steps:
-      - name: Upload result file
-        uses: actions/upload-artifact@v3
-        with:
-          name: html-quality-result
-          path: result.txt
+      - name: Approval Status
+        run: |
+          echo "-------------------------------------"
+          echo "El VB ha sido aprobado."
+          echo "-------------------------------------"
